name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "eb181825-a938-4ffe-9fd8-8d5fa8e236c6"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
